### ISSUE TITLE
控制中心的媒体控制面板上多了个5G开关

### ISSUE THREAD

**Issue by SpeedPartner** [buffcow/Hyper5GSwitch#1]
无字开关,但是关闭后确实会变为4G信号.
辛苦大佬修一下~

**Comment by buffcow** [comment]
> 无字开关,但是关闭后确实会变为4G信号. 辛苦大佬修一下~

截图看看

**Comment by SpeedPartner** [comment]
![Screenshot_2023-12-16-23-04-12-831_com miui home](https://github.com/buffcow/Hyper5GSwitch/assets/6158590/dd9afbb2-4691-4cb3-bb50-174be8e6abde)
并不是每次都会出现开关, 但是大概率吧...
小米14Pro, 安卓14, OS1.0.25.0.UNBCNXM

**Comment by buffcow** [comment]
好的，改天修一下
